### ISSUE TITLE
Add link to standardkontenrahmen.de in GitHub project

### ISSUE THREAD

**Issue by almereyda** [baltpeter/standardkontenrahmen.de#1]
GitHub project descriptions allow to link to a public page, such as standardkontenrahmen.de.

For ease of accessibility of the site, this could be added in this project, too.

**Comment by baltpeter** [comment]
Hi,

thanks for the nudge. :) I have now finally gotten around to writing a proper README.

Cheers!

**Comment by almereyda** [comment]
Danke!

Vielen Dank für die Seite.
